const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    extend: {
        screens: {
            xs: '325px',
            '2xs': '414px',
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1536px',
        },
        colors: {
            '--color-primary': 'var(--color-primary)',
            '--color-secondary': 'var(--color-secondary)',
            'btn-background-primary': 'var(--btn-background-primary)',
            'btn-background-secondary': 'var(--btn-background-secondary)',
            'btn-text-primary': 'var(--btn-text-primary)',
            'btn-text-secondary': 'var(--btn-text-secondary)',
            'btn-border-primary': 'var(--btn-border-primary)',
            'btn-border-secondary': 'var(--btn-border-secondary)',
            'btn-hover-background-secondary': 'var(--btn-hover-background-secondary)',
            /*
            'advanced-level': 'var(--advanced-level)',
            'basic-level': 'var(--basic-level)',
            'basic-sky': 'var(--basic-sky)',
            'blue-indigo': 'var(--blue-indigo)',
            'btn-indigo': 'var(--btn-indigo)',
            'cyan-primary': 'var(--cyan-primary)',
            'cyan-shaded': 'var(--cyan-shaded)',
            'elite-level': 'var(--elite-level)',
            'expert-level': 'var(--expert-level)',
            'gris-claro': 'var(--gris-claro)',
            'gris-perla': 'var(--gris-perla)',
            'intermediate-level': 'var(--intermediate-level)',
            black: 'var(--black)',
            'paris-light-grey': 'var(--daisygray)',
            silver: 'var(--silver)',
            'preferential-level': 'var(--preferential-level)',
            'purple-blue': 'var(--purple-blue)',
            'purple-dark': 'var(--purple-dark)',
            'purple-solid': 'var(--purple-solid)',
            'purple-strong': 'var(--purple-strong)',
            green: 'var(--green)',
            'basic-gray': 'var(--basic-gray)',
            blackfont: 'var(--blackfont)',
            'back-gray': 'var(--back-gray)',
            'light-blue': 'var(--light-blue)',
            'badge-gray': 'var(--badge-gray)',
            'dark-gray': 'var(--dark-gray)',
            nobel: 'var(--nobel)',
            red: 'var(--red)',
            'green-claro': 'var(--bg-green)',
            'orange-oscuro': 'var(--orange-border-alert)',
            magenta: 'var(--magenta)',
            'magenta-pastel': 'var(--magenta-pastel)',
            'cyan-strong': 'var(--cyan-strong)',
            'error-red': 'var(--error-red)',
            'success-green': 'var(--success-green)',
            'indigo-pastel': 'var(--indigo-pastel)',
            terra: 'var(--terra)',
            'gray-light': 'var(--theme-palette-grey-light)',*/
        },
        backgroundColor: (theme) => ({
            ...theme('colors'),
        }),
        gradientColorFrom: (theme) => ({
            transparent: 'transparent',
            white: 'var(--theme-common-white)',
        }),
        gradientColorStops: (theme) => ({
            transparent: 'transparent',
            white: 'var(--theme-common-white)',
        }),
        fontFamily: {
            'open-sans': ['"Open Sans"', ...defaultTheme.fontFamily.sans],
            'azo-sans': ['"Azo Sans"', ...defaultTheme.fontFamily.sans],
            'azo-sans-md': ['"Azo Sans Md"', ...defaultTheme.fontFamily.sans],
        },
        fontSize: {
            xxs: ['1rem', { lineHeight: '1.2rem' }],
            xs: ['1.2rem', { lineHeight: '1.6rem' }],
            sm: ['1.4rem', { lineHeight: '2rem' }],
            base: ['1.6rem', { lineHeight: '2.4rem' }],
            lg: ['1.8rem', { lineHeight: '2.8rem' }],
            xl: ['2rem', { lineHeight: '1.75rem' }],
            '2xl': ['2.4rem', { lineHeight: '3.2rem' }],
            '3xl': ['3rem', { lineHeight: '3.6rem' }],
            '4xl': ['3.6rem', { lineHeight: '4rem' }],
            '5xl': ['4.8rem', { lineHeight: '1' }],
            '6xl': ['6rem', { lineHeight: '1' }],
            '7xl': ['7.2rem', { lineHeight: '1' }],
            '8xl': ['9.6rem', { lineHeight: '1' }],
            '9xl': ['12.8rem', { lineHeight: '1' }],
        },
        fontWeight: {
            thin: '100',
            extralight: '200',
            light: '300',
            normal: '400',
            medium: '500',
            titleBold: '565',
            semibold: '600',
            bold: '700',
            extrabold: '800',
            black: '900',
        },
        minHeight: {
            0: '0px',
            200: '200px',
            full: '100%',
            screen: '100vh',
        },
        minWidth: {
            0: '0',
            '1/4': '25%',
            '1/2': '50%',
            '3/4': '75%',
            '5/6': '83.333333%',
            full: '100%',
            xs: '340px',
            sm: '440px',
            md: '540px',
            lg: '640px',
            xl: '1280px',
            '2xl': '1536px',
        },
        height: (theme) => ({
            auto: 'auto',
            ...theme('spacing'),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.666667%',
            '2/6': '33.333333%',
            '3/6': '50%',
            '4/6': '66.666667%',
            '5/6': '83.333333%',
            full: '100%',
            content: 'max-content',
            screen: '100vh',
        }),
        spacing: {
            px: '1px',
            0: '0px',
            0.5: '0.2rem',
            0.7: '0.3rem',
            1: '0.4rem',
            1.5: '0.6rem',
            2: '0.8rem',
            2.5: '1rem',
            3: '1.2rem',
            3.5: '1.4rem',
            4: '1.6rem',
            5: '2rem',
            5.5: '2.1rem',
            6: '2.4rem',
            7: '2.8rem',
            7.5: '3rem',
            8: '3.2rem',
            9: '3.6rem',
            10: '4rem',
            11: '4.4rem',
            12: '4.8rem',
            13: '5.2rem',
            14: '5.6rem',
            15: '6rem',
            16: '6.4rem',
            20: '8rem',
            20.5: '8.6rem',
            24: '9.6rem',
            28: '11.2rem',
            30: '12rem',
            32: '12.8rem',
            34: '13.6rem',
            36: '14.4rem',
            38: '15.4rem',
            40: '16rem',
            44: '17.6rem',
            46: '18.4rem',
            48: '19.2rem',
            52: '20.8rem',
            53: '21.2rem',
            54: '21.6rem',
            56: '22.4rem',
            60: '24rem',
            64: '25.6rem',
            68: '27.2rem',
            72: '28.8rem',
            80: '32rem',
            84: '33.6rem',
            86: '34.3rem',
            88: '35.2rem',
            88.5: '35.5rem',
            92: '36.8rem',
            96: '38.4rem',
            96.5: '38.7rem',
            98: '38.7rem',
            100: '40rem',
            104: '41.6rem',
            340: '340px',
            361: '361px',
            450: '450px',
            480: '480px',
            855: '855px',
        },
        scale: {
            0: '0',
            25: '.25',
            50: '.5',
            75: '.75',
            90: '.9',
            95: '.95',
            100: '1',
            105: '1.05',
            110: '1.1',
            125: '1.25',
            150: '1.5',
            200: '2',
        },
        rotate: {
            '-180': '-180deg',
            '-90': '-90deg',
            '-45': '-45deg',
            '-12': '-12deg',
            '-6': '-6deg',
            '-3': '-3deg',
            '-2': '-2deg',
            '-1': '-1deg',
            0: '0deg',
            1: '1deg',
            2: '2deg',
            3: '3deg',
            6: '6deg',
            12: '12deg',
            45: '45deg',
            90: '90deg',
            180: '180deg',
        },
        lineHeight: {
            none: '1',
            tight: '1.25',
            snug: '1.375',
            normal: '1.5',
            relaxed: '1.625',
            loose: '2',
            3: '1.35rem',
            4: '1.6rem',
            5: '1.85rem',
            6: '2.1rem',
            7: '2.35rem',
            8: '2.6rem',
            9: '2.85rem',
            10: '3.1rem',
        },
        zIndex: {
            0: 0,
            10: 10,
            20: 20,
            30: 30,
            40: 40,
            50: 50,
            25: 25,
            75: 75,
            100: 100,
            max: 999999999,
            auto: 'auto',
        },
        borderRadius: {
            none: '0px',
            sm: '0.2rem',
            DEFAULT: '0.4rem',
            md: '0.6rem',
            lg: '0.8rem',
            xl: '1.2rem',
            '2xl': '1.6rem',
            '3xl': '2.4rem',
            full: '9999px',
        },
        maxWidth: (theme, { breakpoints }) => ({
            none: 'none',
            0: '0rem',
            xs: '32rem',
            sm: '38.4rem',
            md: '44.8rem',
            lg: '51.2rem',
            xl: '57.6rem',
            '2xl': '67.2rem',
            '3xl': '76.8rem',
            '4xl': '89.6rem',
            '5xl': '102.4rem',
            '6xl': '115.2rem',
            '7xl': '128rem',
            full: '100%',
            min: 'min-content',
            max: 'max-content',
            prose: '65ch',
            ...breakpoints(theme('screens')),
        }),
        maxHeight: (theme) => ({
            ...theme('spacing'),
            full: '100%',
            screen: '100vh',
            max: 'max-content',
        }),
    },
    boxShadow: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        DEFAULT:
            '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
        inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
        none: 'none',
        'card-default': '0px 2px 8px 0px #1A1A1A1A',
        'button-default': '2px 4px 10px rgb(0 125 179 / 10%)',
    },
};
